services:
  postgres:
    image: postgres:15-alpine
    container_name: floci-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: floci_ui
      POSTGRES_USER: floci_ui
      POSTGRES_PASSWORD: 1100
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  floci:
    image: floci/floci:latest
    container_name: floci-aws
    ports:
      - "4566:4566"
      - "4500:4500"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./floci-data:/app/data
    environment:
      - SERVICES=s3
      - FLOCI_STORAGE_MODE=persistent
      - FLOCI_STORAGE_PERSISTENT_PATH=/app/data
    restart: unless-stopped